### PR TITLE
use new response dialog constants

### PR DESCRIPTION
**Pull request by cedlemo**
Just a 

    find ./ruby-gnome/gtk3 -type f | xargs sed -i 's/Gtk::Dialog::RESPONSE_/Gtk::ResponseType::/g'

and a simple update of button2.rb

### CODE REVIEW

**Comment by kou** [comment]
Thanks for your pull request.
But it has unrelated comment: https://github.com/cedlemo/ruby-gnome2/commit/7342af7072183cae0e7ad0dfad7bb1a1cbeadadc

Could you create a new pull request that has only https://github.com/cedlemo/ruby-gnome2/commit/30529ec002bf7595edfc2edd5c8aae104bc50ed6 ?

The following command lines may help you:

```text
% git checkout -b use-new-response-dialog-constants upstream/master
% git cherry-pick 30529ec002bf7595edfc2edd5c8aae104bc50ed6
% git push -u origin use-new-response-dialog-constants
% git checkout master # optional
```

**Comment by cedlemo** [comment]
I have followed your instructions. Even if I don't really fully understand them. It seems that I have created a new branch where I have applied the commit 30529ec002bf7595edfc2edd5c8aae104bc50ed6 and I pushed this modified branch on my repo then I created a pull requested.

So ok but I don't see how to clean my mess.

What is the best way to work and to sent you a pull request.

I create local branch for each pb I want to solve, then I merge them on master then I push the commits on my remote github (which is a fork of your), then I create a pull request for you. But it seems that each commit I do are joined in the same pull request . I think it 's not the right way.

**Comment by kou** [comment]
> So ok but I don't see how to clean my mess.
> 
> What is the best way to work and to sent you a pull request.

OK. I describe about the best way.

Short description: The best way is using one branch per pull request.

Long description:

GitHub associates one branch to one pull request. If you change the branch (for example, commit and push), the change is applied in the associated pull request.

If you use only one branch for multiple pull requests, all pull requests includes all changed in your only one branch. It's not expected way.

It's best way that you create new branch for each pull request. If you do it, your change for other pull request isn't appeared in other pull request.

> I create local branch for each pb I want to solve, then I merge them on master then I push the commits on my remote github (which is a fork of your), then I create a pull request for you. But it seems that each commit I do are joined in the same pull request . I think it 's not the right way.

You just use your each local branch for corresponding pull request. You don't need to merge your local branches into your master.

I hope that the description resolves your mess.

**Comment by cedlemo** [comment]
Ok it is clear for me, 
*    I create a new branch, make my modifications, 
*    commit them on this branch
*    push on my remote with <code>git push -u origin my-new-branch</code>
*    create a pull request for you
*    you accept it then I sync my local and remote master 

For now, it remains the problems of the commits you just rejected, my forked repos is not even with your. I have read that with git you cannot remove commit. Should I have to delete my forked repo and recreate it?

**Comment by kou** [comment]
> For now, it remains the problems of the commits you just rejected, my forked repos is not even with your. I have read that with git you cannot remove commit. Should I have to delete my forked repo and recreate it?

You don't recreate your repository. You just create a branch and reset your master to master of ruby-gnome2/ruby-gnome2 repository like the following:

```text
% git checkout -b XXX upstream/master
% git cherry-pick 7342af7072183cae0e7ad0dfad7bb1a1cbeadadc
% git push -u origin XXX
% git checkout master
% git reset --hard upstream/master
```

**Comment by cedlemo** [comment]
Thank you

**Pull request closed without merging**
