### PR TITLE
Gtk::Image #new manage resource file

### PR DESCRIPTION
**Pull request by cedlemo**
I have modified the test-gtk-image.rb so that it looks like other test scripts (test-gtk-builder.rb)

I still have a problem with the test for the resource. For example the `image.resource` returns nil.
I will do an issue for this.

### CODE REVIEW

**Comment by kou** [comment]
Thanks.
I've confirmed that `image.resource` always returns `nil`.

It seems that it's a GTK+ bug. I think that this patch is needed for GTK+:

```diff
diff --git a/gtk/gtkimage.c b/gtk/gtkimage.c
index 5763f06..032100d 100644
--- a/gtk/gtkimage.c
+++ b/gtk/gtkimage.c
@@ -1015,8 +1015,6 @@ gtk_image_set_from_resource (GtkImage    *image,
       return;
     }
 
-  priv->resource_path = g_strdup (resource_path);
-
   if (gdk_pixbuf_animation_is_static_image (animation))
     gtk_image_set_from_pixbuf (image, gdk_pixbuf_animation_get_static_image (animation));
   else
@@ -1024,6 +1022,8 @@ gtk_image_set_from_resource (GtkImage    *image,
 
   _gtk_icon_helper_set_pixbuf_scale (priv->icon_helper, scale_factor);
 
+  priv->resource_path = g_strdup (resource_path);
+
   g_object_notify (G_OBJECT (image), "resource");
 
   g_object_unref (animation);
```

`resource_path` set at https://git.gnome.org/browse/gtk+/tree/gtk/gtkimage.c?id=48ea0cbe4b8bcd37958601d39b9e93be7d28fa8b#n1018

```c
  priv->resource_path = g_strdup (resource_path);
```

is cleared at https://git.gnome.org/browse/gtk+/tree/gtk/gtkimage.c?id=48ea0cbe4b8bcd37958601d39b9e93be7d28fa8b#n1021 or https://git.gnome.org/browse/gtk+/tree/gtk/gtkimage.c?id=48ea0cbe4b8bcd37958601d39b9e93be7d28fa8b#n1023

```c
  if (gdk_pixbuf_animation_is_static_image (animation))
    gtk_image_set_from_pixbuf (image, gdk_pixbuf_animation_get_static_image (animation));
  else
    gtk_image_set_from_animation (image, animation);
```

because both `gtk_image_set_from_pixbuf()` and `gtk_image_set_from_animation()` call `gtk_image_clear()`. `gtk_image_clear()` calls `gtk_image_reset()` https://git.gnome.org/browse/gtk+/tree/gtk/gtkimage.c?id=48ea0cbe4b8bcd37958601d39b9e93be7d28fa8b#n1815 and `gtk_image_reset()` clears `priv->resource_path` https://git.gnome.org/browse/gtk+/tree/gtk/gtkimage.c?id=48ea0cbe4b8bcd37958601d39b9e93be7d28fa8b#n1792 .

So `priv->resourse_path` set by `gtk_image_set_from_resource()`  is cleared. I think that it's unexpected result. The above patch will fix the problem.

Could you report this to GTK+ Bugzilla? https://bugzilla.gnome.org/enter_bug.cgi

**Comment by cedlemo** [comment]
Of course.

**Comment by kou** [comment]
Thanks!

**Comment by cedlemo** [comment]
You can find the Gtk3 issue here https://bugzilla.gnome.org/show_bug.cgi?id=751443. I hope that the way I presented it, suits you.

Regards

**Comment by kou** [comment]
It has been merged. Great!

**Pull request merged**
