### PR TITLE
Gtk::ColorSelectionDialog with hash arguments

### PR DESCRIPTION
**Pull request by cedlemo**
I had had to add an empty string if no title was provided otherwise the test complains with:

    TypeError: no implicit conversion of nil into String

### CODE REVIEW

**Comment by kou** [comment]
Thanks for your work!
But we don't support `Gtk::ColorSelectionDialog` because [gtk_color_selection_dialog_new()](https://developer.gnome.org/gtk3/stable/GtkColorSelectionDialog.html#gtk-color-selection-dialog-new) is deprecated in GTK+ 3.

Sorry...

**Comment by kou** [comment]
FYI: GTK+ introduces `Gtk::ColorChooserDialog` for color choosing widget.

**Comment by cedlemo** [comment]
Yes I was aware of ColorChooserDialog. It is just that there were no deprecated error messages and I didn't search further. It is  me who is sorry. Next time I will check.

**Comment by kou** [comment]
Thanks!

**Pull request closed without merging**
