### PR TITLE
Gtk3 sample misc text buffer serialize

### PR DESCRIPTION
**Pull request by cedlemo**
add missing stuff for Gtk::TextBuffer

### CODE REVIEW

**Comment by kou** [comment]
Umm... "Merge pull request" button is disabled.
Could you rebase on master?

**Comment by cedlemo** [comment]
Rebase on master done.

**Comment by kou** [comment]
Umm "Merge pull request" button is still disabled...
Why...

**Comment by kou** [comment]
Could you try the following?

```text
% cd /tmp
% git clone git@github.com:cedlemo/ruby-gnome2.git
% cd ruby-gnome2
% git remote add upstream git@github.com:ruby-gnome2/ruby-gnome2.git
% git fetch --all
% git rebase upstream/master
% git push # It may be failed. If it is failed, please let me know.
% git checkout gtk3_sample_misc_text_buffer_serialize
% git rebase origin/master
% git push --force
```

**Comment by cedlemo** [comment]
I have done everything you asked. It looks like you know exactly what was the problem. Do you think that I need to delete my local copy (which I use to create the modification) and recreate it?

**Comment by kou** [comment]
Thanks! I can merge your pull request.

But... I don't know why you need to recreate your local repository... Sorry...

**Pull request merged**
