### PR TITLE
check existence of Makefile before running make

### PR DESCRIPTION
**Pull request by dai-vdr**
this fix use other tests as reference.

### CODE REVIEW

**Comment by kou** [comment]
When do we need this change?

**Comment by dai-vdr** [comment]
This is needed when testing without building package.

Debian CI uses pre-built binary package (test target) and no-built source package (test case).
For example, see [ruby-cairo's test log](https://ci.debian.net/packages/r/ruby-cairo/unstable/amd64/). It does not run extconf.rb and does not generate Makefile.

**Comment by kou** [comment]
OK. I've merged.

**Comment by dai-vdr** [comment]
Thank you very much!

**Pull request merged**
