### PR TITLE
Include GdkPixbuf::Pixbuf into Gdk

### PR DESCRIPTION
**Pull request by cedlemo**
With this, all is working fine. What do you want me to do next?

Continue the gtk-demos or finish the tests for gdk_pixbufs. I would prefer finish the tests for the implemented options and functions of GdkPixbuf.

### CODE REVIEW

**Comment by kou** [comment]
It's not needed. I've already implemented it in `gdk_pixbuf2/lib/gdk_pixbuf2/deprecated.rb`.

> Continue the gtk-demos or finish the tests for gdk_pixbufs. I would prefer finish the tests for the implemented options and functions of GdkPixbuf.

I agree with you. Writing tests of gdk_pixbuf2 is better.

**Comment by cedlemo** [comment]
> It's not needed. I've already implemented it in gdk_pixbuf2/lib/gdk_pixbuf2/deprecated.rb

@kou I am lost, gdk require gdk_pixbuf2 and in the deprecated.rb you open the gdk module with:

```ruby
module Gdk
  extend GLib::Deprecatable

  define_deprecated_const :Pixbuf, "GdkPixbuf::Pixbuf"
  define_deprecated_const :PixbufAnimation, "GdkPixbuf::PixbufAnimation"
  define_deprecated_const :PixbufLoader, "GdkPixbuf::PixbufLoader"
  define_deprecated_const :PixbufSimpleAnim, "GdkPixbuf::PixbufSimpleAnim"
  define_deprecated_const :Pixdata, "GdkPixbuf::Pixdata"
end
```
I don't see how it does the same job that the instruction `include GdkPixbuf`.

**Comment by kou** [comment]
`GLib::Deprectable` installs `const_missing` hook. The hook reports a warning when deprecated constant name (e.g. `:Pixbuf`) defined by `define_deprecated_const` is referenced. The hook returns new value (e.g. `"GdkPixbuf::Pixbuf"`) with deprecated constant name (e.g. `Gdk::Pixbuf`).

This is how to provide `Gdk::Pixbuf`.

**Comment by cedlemo** [comment]
Thanks a lot, it is really clear now.

**Pull request closed without merging**
