### PR TITLE
Add a TODO list

### PR DESCRIPTION
**Pull request by cedlemo**
I don't know if you will agree with this but as I like to have an overview of what I am doing and I always use a list of the things I have to do. To put this list here could be more convenient for me and could be usefull for other people who would like to help.

### CODE REVIEW

**Comment by cosmo0920** [comment]
FYI, GitHub issue support following checklist syntax.

---

```log
- [ ] TODO
```

will be rendered as:

- [ ] TODO

---

And 

```log
- [x] TODO
```

will be rendered as:

- [x] TODO

---

How about use this TODO list syntax in issue and manage in this issue?

**Comment by cosmo0920** [comment]
Or you can use csv file.

Please refer to this GitHub help: https://help.github.com/articles/rendering-csv-and-tsv-data/

**Comment by cedlemo** [comment]
That looks great (especially the csv), I didn't know that was possible. Thanks @cosmo0920.

I will let this pull and wait for @kou 's opinion.

**Comment by kou** [comment]
I've merged it because it's convenient for @cedlemo.
@cedlemo, if you want to use GitHub's TODO list feature, you can change your task management tool anytime. :-)

**Comment by cedlemo** [comment]
Thanks a lot @kou

**Pull request merged**
