### PR TITLE
Glib2 regex capture count

### PR DESCRIPTION
**Pull request by cedlemo**
This one should be OK

### CODE REVIEW

**Comment by kou** [comment]
Ah, sorry.
Could you rebase on master? #684 conflicts with it.

**Comment by cedlemo** [comment]
Yes of course.
For each pull request I create them using:

    git checkout -b mybranch upstream/master

Is there a better way that make the thing easier for you?

**Comment by kou** [comment]
Use the following!:

```text
git checkout mybranch
git fetch --all
git rebase upstream/master
```

**Comment by kou** [comment]
Thanks!

**Pull request merged**
